#!/bin/bash


docker run -itd --name mokey --privileged -h mokey.tcc.local -v /sys/fs/cgroup:/sys/fs/cgroup:ro --tmpfs /tmp --tmpfs /run --tmpfs /run/lock -p 8084:8084 --add-host ipa.tcc.local:192.168.7.7 --dns 192.168.7.7 mokey

docker exec -t mokey bash -c 'systemctl enable mariadb'
docker exec -t mokey bash -c 'systemctl start mariadb'

docker exec -t mokey bash -c "/install.sh"

docker exec -t mokey bash -c 'systemctl enable mokey'
docker exec -t mokey bash -c 'systemctl start mokey'
